### ISSUE TITLE
Component views can't return arrays

### ISSUE THREAD

**Issue by milesmatthias** [mrsweaters/mithril-rails#8]
See my commented snippet below:

```js

/** @jsx m */

MyApp.TestComponent = {};
MyApp.TestComponent.controller = function(){
};
MyApp.TestComponent.view = function(ctrl){
  return <h1>COMPONENT WORKS</h1>;

  /*
    // THIS DOESN'T WORK FOR SOME REASON

    return [
      <h1>Hello World</h1>
    ];
  */
};


var testBody = function(ctrl) {
    return [
        <section class="page-section -pad-y -bg-gray">
          <div class="subsection">
            <div class="textblock -center -pad-y">

              <h3>Hi hi</h3>
              <br/><br/>

              {m.component(EEApp.TestComponent)}

            </div>
          </div>
        </section>

    ]
};
```

Here's the error that mithril gives in the console if I use my uncommented `return` statement:

```
Uncaught Error: Component template must return a virtual element, not an array, string, etc.
```

**Comment by mrsweaters** [comment]
This sounds like a limitation of Mithril's view syntax. Have you tried wrapping it in a `m` function?

```
m("div", [<h1>Hello World</h1>])
```

Or:

```
m("div", ['<h1>Hello World</h1'>])
```

**Comment by pobri19** [comment]
I'm having this problem as well. Wrapping it in a div works, but I don't want an unnecessary div floating around for no reason. The console errors with this if I try and return an array:

Error: Component template must return a virtual element, not an array, string, etc.
...,fb.push(ib)}if(!l.tag&&fb.length)throw new Error("Component template must retur...

**Comment by mrsweaters** [comment]
@milesmatthias Release 0.0.7 should fix your issue.
