### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by kaukas** [mrsweaters/mithril-rails#9]
Hello.

Thank you for the effort to integrate Mithril into Rails. However, it seems to me the bundled Mithril library is 6 months old and the JSXTansformer is used instead of MSXTransformer. Would you accept improvements on both of these?

Thank you!

**Comment by mrsweaters** [comment]
@kaukas Thanks for letting me know. Absolutely, if you'd like to submit a pull request I'll merge it in.

**Comment by mrsweaters** [comment]
@ketan Thank you for taking the time to make those changes. @kaukas Up to date now.
